#!/bin/bash
# Clean build artifacts while preserving the sipp executable

set -e

echo "Cleaning build artifacts..."

# Remove object files and test binaries
echo "  Removing object files and test binaries..."
rm -f *.o sipp_unittest

# Remove test and log files
echo "  Removing test logs..."
rm -f sipp_unittest.log sipp_unittest.trs test-suite.log

# Remove build directories
echo "  Removing build directories..."
rm -rf .deps autom4te.cache

# Remove generated configuration files
echo "  Removing generated configuration files..."
rm -f Makefile Makefile.in config.log config.status
rm -f include/config.h include/stamp-h1

# Remove autotools helper scripts and generated files (regenerated by autoreconf)
echo "  Removing autotools helper scripts and generated files..."
rm -f compile depcomp install-sh missing test-driver
rm -f aclocal.m4 configure

# Remove backup files
echo "  Removing backup files..."
rm -f config.guess~ config.sub~ configure~ *~

# Verify sipp binary still exists
if [ -f sipp ]; then
    echo "✓ Clean complete. sipp binary preserved ($(du -h sipp | cut -f1))"
else
    echo "✓ Clean complete. No sipp binary found."
fi

echo ""
echo "To rebuild:"
echo "  autoreconf -ivf"
echo "  ./configure --with-openssl --with-pcap CPPFLAGS=\"-I/opt/homebrew/opt/openssl@3.6/include\" LDFLAGS=\"-L/opt/homebrew/opt/openssl@3.6/lib\""
echo "  make"
